[tool.poetry]
name = "rosreestr2coord"
version = "4.1.5"
license = "MIT"
description = "Get coordinates of area by cadastral number"
authors = ["Artemiy Doroshkov <rendrom@gmail.com>"]
readme = 'README.md'
repository = "https://github.com/rendrom/rosreestr2coord"
homepage = "https://github.com/rendrom/rosreestr2coord"

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.24"
opencv-python = "^4.6"
Pillow = "^9.1"
matplotlib = "^3.5"

[tool.poetry.dev-dependencies]
pytest = '^5.0'
pytest-cov = '^2.4'
tox = '^3.4'
mypy = '*'
flake8 = '*'
flake8-quotes = '*'

[tool.poetry.scripts]
rosreestr2coord = 'scripts.console:main'
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[mypy]
ignore_missing_imports = true
show_error_context = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_subclassing_any = false
warn_no_return = true
strict_optional = true
no_implicit_optional = true
disallow_any_generics = true
disallow_any_unimported = false
warn_redundant_casts = true
warn_unused_configs = true
show_traceback = true
always_false = 'MYPYC'
