version: '3.4'

services:
  webgateway:
    image: ${DOCKER_REGISTRY-}webgateway
    ports:
      - "5001:443"
    build:
      context: .
      dockerfile: Microservices/Microservice.DashboardManager/Dockerfile

  dbmanager.microservice:
    image: ${DOCKER_REGISTRY-}dbmanagermicroservice
    ports:
      - "5100:443"
    build:
      context: .
      dockerfile: Microservices/DbManager.Microservice/Dockerfile


  removeexpiredlinks.microservice:
    image: ${DOCKER_REGISTRY-}removeexpiredlinksmicroservice
    ports:
      - "5101:443"
    build:
      context: .
      dockerfile: Microservices/Tasks/RemoveExpiredLinks.Microservice/Dockerfile


  payment.microservice:
    image: ${DOCKER_REGISTRY-}paymentmicroservice
    ports:
      - "5102:443"
    build:
      context: .
      dockerfile: Microservices/Payment.Microservice/Dockerfile

