version: '3.4'

services:
  microservice.dashboardmanager:
    image: ${DOCKER_REGISTRY-}microservicedashboardmanager
    ports:
      - "49162:49162"
    build:
      context: .
      dockerfile: Microservices/Microservice.DashboardManager/Dockerfile

  microservice.mapmanager:
    image: ${DOCKER_REGISTRY-}microservicemapmanager
    ports:
      - "49165:49165"
    build:
      context: .
      dockerfile: Microservices/Microservice.MapManager/Dockerfile

  microservice.subscriptionmanager:
    image: ${DOCKER_REGISTRY-}microservicesubscriptionmanager
    ports:
      - "49169:49169"
    build:
      context: .
      dockerfile: Microservices/Microservice.SubscriptionManager/Dockerfile

  microservice.modeltaskmanager:
    image: ${DOCKER_REGISTRY-}microservicemodeltaskmanager
    ports:
      - "49171:49171"
    build:
      context: .
      dockerfile: Microservices/Microservice.ModelTaskManager/Microservice.ModelTaskManager/Dockerfile


  microservice.forecastmanager:
    image: ${DOCKER_REGISTRY-}microserviceforecastmanager
    ports:
      - "49173:49173"
    build:
      context: .
      dockerfile: Microservices/Microservice.ForecastManager/Dockerfile

